- params:
    angle_tolerance: 15
    blur_kernel_size: 5
    canny_high: 150
    canny_low: 50
    hough_threshold: 50
    max_line_gap: 10
    min_line_length: 50
  profile_name: 新模板2
  time: '2026-06-05 00:13:44'
- params:
    angle_tolerance: 15
    blur_kernel_size: 5
    canny_high: 150
    canny_low: 50
    hough_threshold: 50
    max_line_gap: 10
    min_line_length: 50
  profile_name: 新模板2
  time: '2026-06-05 00:13:45'
