新模板1:
  angle_tolerance: 15
  blur_kernel_size: 11
  canny_high: 150
  canny_low: 50
  clahe_clip_limit: 2.0
  hough_threshold: 50
  max_line_gap: 10
  min_line_length: 50
默认:
  angle_tolerance: 15
  blur_kernel_size: 5
  canny_high: 150
  canny_low: 50
  clahe_clip_limit: 2.0
  hough_threshold: 50
  max_line_gap: 10
  min_line_length: 50
