'333':
  angle_tolerance: 15
  blur_kernel_size: 5
  clahe_clip_limit: 2.0
  canny_high: 150
  canny_low: 50
  hough_threshold: 131
  max_line_gap: 30
  min_line_length: 203
新模板1:
  angle_tolerance: 15
  blur_kernel_size: 5
  clahe_clip_limit: 2.0
  canny_high: 150
  canny_low: 50
  hough_threshold: 50
  max_line_gap: 10
  min_line_length: 50
新模板2:
  angle_tolerance: 15
  blur_kernel_size: 5
  clahe_clip_limit: 2.0
  canny_high: 150
  canny_low: 50
  hough_threshold: 50
  max_line_gap: 10
  min_line_length: 50
默认:
  angle_tolerance: 15
  blur_kernel_size: 5
  clahe_clip_limit: 2.0
  canny_high: 150
  canny_low: 50
  hough_threshold: 50
  max_line_gap: 10
  min_line_length: 50
